spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usne
    username: usneuser
    password: usneuser
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
